# Site wide configuration

title: fatpixels
locale: en_US
description: Fat pixels from photography and programming.
logo: bloglogo.jpg
search: true
url: http://fatpixels.me

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Alvina Joshi & Krishnashish Gogoi
  avatar: alvkri_bio.jpg
  email: alvina.joshi177 [at] gmail [dot] com
  disqus-shortname: fatpixels
  twitter:
  facebook:
  github: mister-raindrop
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  pinterest:
  google:
    plus: #username
    analytics: UA-53251016-1
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
